// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCard(arg1) {
  return window['go']['main']['App']['AddCard'](arg1);
}

export function DeleteCard(arg1) {
  return window['go']['main']['App']['DeleteCard'](arg1);
}

export function GetCards(arg1) {
  return window['go']['main']['App']['GetCards'](arg1);
}

export function GetStats() {
  return window['go']['main']['App']['GetStats']();
}

export function MoveCard(arg1, arg2) {
  return window['go']['main']['App']['MoveCard'](arg1, arg2);
}

export function RescrapAllCards() {
  return window['go']['main']['App']['RescrapAllCards']();
}

export function Sumprice() {
  return window['go']['main']['App']['Sumprice']();
}

export function UpdateCardPriceFixed(arg1) {
  return window['go']['main']['App']['UpdateCardPriceFixed'](arg1);
}
