// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddCard(arg1:main.AddCardRequest):Promise<main.Card>;

export function DeleteCard(arg1:number):Promise<void>;

export function GetCards(arg1:string):Promise<Array<main.Card>>;

export function GetStats():Promise<Record<string, any>>;

export function MoveCard(arg1:number,arg2:string):Promise<void>;

export function UpdateCardPriceFixed(arg1:number):Promise<main.Card>;
